import builtins from "builtin-modules";
import chokidar from "chokidar";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";

// Dev-only: `pnpm dev` copies the build into this vault so changes appear on reload.
// Set OBSIDIAN_VAULT to your own vault path; the copy step is skipped when unset.
const VAULT_DIR = process.env.OBSIDIAN_VAULT ?? "";
const FILES = ["main.js", "manifest.json", "styles.css"];

// ---

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// --- Pass 1: the inference worker -------------------------------------------
// The engine runs in a Web Worker so prediction never blocks typing. Obsidian's
// community-plugin installer only fetches main.js/manifest.json/styles.css, so a
// sidecar worker .js would not survive an install – instead we bundle the worker
// to a standalone IIFE and inline it into main.js as a string, which the plugin
// turns into a Blob URL at runtime. Must run BEFORE the main build, which imports
// the generated module.
async function buildWorkerSource() {
  const out = await esbuild.build({
    entryPoints: ["src/predictive/inferenceWorker.entry.ts"],
    bundle: true,
    format: "iife",
    target: "es2018",
    platform: "browser",
    // The worker must be self-contained: `obsidian` is main-thread-only, and
    // EngineCore imports nothing from it (settings come in as plain data).
    external: ["obsidian", "electron", ...builtins],
    write: false,
    minify: prod,
    logLevel: "warning",
    legalComments: "none",
  });
  const src = out.outputFiles[0].text;
  const file = "src/predictive/generated/workerSource.ts";
  fs.writeFileSync(
    file,
    "// GENERATED by esbuild.config.mjs – do not edit.\n" +
      "// The inference worker, bundled standalone and inlined (see buildWorkerSource).\n" +
      `export const WORKER_SRC = ${JSON.stringify(src)};\n`,
  );
  console.log(`🧵 inference worker bundled -> ${(src.length / 1024).toFixed(1)} KB inlined`);
}
await buildWorkerSource();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();

  // Without a vault configured there is nothing to copy into - keep watching and
  // rebuilding, but do not create an .obsidian tree inside the repo.
  if (!VAULT_DIR) {
    console.log("👀 Watching. Set OBSIDIAN_VAULT=<path to your vault> to auto-copy the build.");
  } else {

  const pluginDir = path.join(
    VAULT_DIR,
    ".obsidian/plugins/smart-autocorrect",
  );

  console.log(`📁 Creating ${pluginDir} (if not existed)`);
  fs.mkdirSync(pluginDir, { recursive: true });

  const hotreloadPath = path.join(pluginDir, ".hotreload", "");
  console.log(`🌶 Creating a ${hotreloadPath}`);
  fs.writeFileSync(hotreloadPath, "");

  const watcher = chokidar.watch(FILES, { persistent: true });
  watcher
    .on("add", (p) => {
      console.log(`♨  ${p} is added`);
      fs.copyFileSync(p, path.join(pluginDir, p));
    })
    .on("change", (p) => {
      console.log(`♨  ${p} is changed`);
      fs.copyFileSync(p, path.join(pluginDir, p));
    });
  }
}
